# nvidia optimization
backend = "xrender";
vsync = true;

inactive-opacity = 0.85;
active-opacity = 0.95;
frame-opacity = 0.9;

opacity-rule = [
	"100:class_g = 'feh'",
	"100:class_g = 'i3lock'",
	"100:class_g = 'dmenu'"
];

fading = true;

fade-in-step = 0.045;
fade-out-step = 0.045;
fade-delta = 5;
