color0       #3A3C3E
color8       #ACA69F
color1       #C187A5
color9       #C187A5
color2       #F37B4A
color10      #F37B4A
color3       #F8BB9F
color11      #F8BB9F
color4       #FCC2D0
color12      #FCC2D0
color5       #F7E78E
color13      #F7E78E
color6       #FCECD8
color14      #FCECD8
color7       #F5EDE3
color15      #F5EDE3