enabled_layouts splits,stack
linux_display_server X11

# 禁用桌面通知以避免 dbus portal 问题
enable_audio_bell no
wayland_enable_ime no

touch_scroll_multiplier 1.0

map ctrl+d launch --location=hsplit
map ctrl+k launch --location=vsplit
map ctrl+w close_window
#Fonts
# font_family Fira Code
# bold_font auto
# italic_font auto
# bold_italic_font auto
font_size 26.0 

term xterm-256color

# BEGIN_KITTY_FONTS
font_family      Iosevka
bold_font        auto
italic_font      auto
bold_italic_font auto

background #242424
# END_KITTY_FONTS

